"""Auto-generate a README.md alongside each exported model.

Writes a markdown file documenting:
  * which recipe produced this model
  * dataset stats (number of rows, mode)
  * eval scores if `eval-report.json` is present
  * checkpoint hash (deterministic over file contents)
  * how to load the model in Ollama / transformers

This is reproducibility hygiene: the user gets back what they did without
manually tracking it. The function is called from the CLI `export` command
when `--write-readme` is on (default True).
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import asdict
from pathlib import Path

logger = logging.getLogger(__name__)


def hash_checkpoint_dir(checkpoint_dir: Path) -> str:
    """Compute a deterministic short hash over a checkpoint's safetensors."""
    h = hashlib.sha256()
    files = sorted(
        p for p in checkpoint_dir.rglob("*")
        if p.is_file() and p.suffix in {".safetensors", ".bin", ".json", ".txt"}
    )
    for fp in files:
        h.update(fp.name.encode("utf-8"))
        try:
            with fp.open("rb") as f:
                while chunk := f.read(1 << 16):
                    h.update(chunk)
        except OSError as e:
            logger.debug("hash skip %s: %s", fp, e)
    return h.hexdigest()[:12]


def _read_dataset_stats(workspace: Path) -> dict[str, int | str]:
    """Count rows of dataset_qa.jsonl or dataset_raw.jsonl."""
    for fname in ("dataset_qa.jsonl", "dataset_raw.jsonl"):
        p = workspace / fname
        if not p.exists():
            continue
        n = 0
        with p.open("r", encoding="utf-8") as f:
            for ln in f:
                if ln.strip():
                    n += 1
        return {"file": fname, "rows": n, "mode": "sft" if "qa" in fname else "cpt"}
    return {"file": "", "rows": 0, "mode": "unknown"}


def _read_eval(eval_path: Path) -> dict | None:
    if not eval_path.exists():
        return None
    try:
        return json.loads(eval_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def write_run_readme(
    *,
    workspace: Path,
    export_dir: Path,
    export_format: str,
    quant: str | None = None,
) -> Path:
    """Write `<export_dir>/README.md` with run metadata.

    Returns the path to the written README. Idempotent: overwrites existing.
    """
    from jw_finetune.recipes.base import recipe_from_yaml

    export_dir.mkdir(parents=True, exist_ok=True)
    out = export_dir / "README.md"

    recipe_path = workspace / "recipe.yaml"
    recipe_dict: dict = {}
    if recipe_path.exists():
        try:
            r = recipe_from_yaml(recipe_path)
            recipe_dict = asdict(r)
        except Exception as e:  # noqa: BLE001
            logger.warning("Could not read recipe: %s", e)

    dataset_stats = _read_dataset_stats(workspace)
    eval_data = _read_eval(workspace / "eval-report.json")
    ckpt_dir = workspace / "checkpoints" / "final"
    ckpt_hash = hash_checkpoint_dir(ckpt_dir) if ckpt_dir.exists() else "n/a"

    lines: list[str] = [
        "# jw-finetune model export",
        "",
        "> Auto-generated by `jw-finetune export`. Reproducibility receipt for this trained model.",
        "",
        "## Recipe",
        "",
        f"- **name**: `{recipe_dict.get('name', 'n/a')}`",
        f"- **task**: `{recipe_dict.get('task', 'n/a')}`",
        f"- **base model**: `{recipe_dict.get('base_model', 'n/a')}`",
        f"- **languages**: {recipe_dict.get('languages', [])}",
        f"- **qa_style**: `{recipe_dict.get('qa_style', 'n/a')}`",
        f"- **epochs**: {recipe_dict.get('epochs', 'n/a')}",
        f"- **lora_rank** / **lora_alpha**: {recipe_dict.get('lora_rank', 'n/a')} / {recipe_dict.get('lora_alpha', 'n/a')}",
        f"- **chat_template**: `{recipe_dict.get('chat_template', 'n/a')}`",
        f"- **use_rslora**: {recipe_dict.get('use_rslora', False)}",
        f"- **train_on_responses_only**: {recipe_dict.get('train_on_responses_only', True)}",
        "",
        "## Dataset",
        "",
        f"- **mode**: {dataset_stats.get('mode')}",
        f"- **rows**: {dataset_stats.get('rows')}",
        f"- **file**: `{dataset_stats.get('file')}`",
        "",
    ]

    if eval_data:
        lines += [
            "## Evaluation",
            "",
            f"- **prompts**: {eval_data.get('n_prompts', 'n/a')}",
            f"- **citation accuracy**: {eval_data.get('citation_accuracy', 0):.2%}",
            f"- **terminology score**: {eval_data.get('terminology_score', 0):.2%}",
            "",
        ]

    lines += [
        "## Export",
        "",
        f"- **format**: `{export_format}`",
        f"- **quantization**: `{quant or 'n/a'}`",
        f"- **checkpoint hash**: `{ckpt_hash}`",
        f"- **workspace**: `{workspace}`",
        "",
        "## Loading the model",
        "",
        "### Ollama",
        "",
        "```bash",
        f"cd {export_dir.name}",
        "cat > Modelfile <<EOF",
        f"FROM ./model-{(quant or 'Q4_K_M').lower()}.gguf",
        'SYSTEM "Eres un asistente que responde con doctrina JW respetuosa."',
        "EOF",
        f"ollama create {recipe_dict.get('name', 'my-jw-model')} -f Modelfile",
        "```",
        "",
        "### Python (jw-agents)",
        "",
        "```python",
        "from jw_agents.finetuned_model import build_client",
        f"client = build_client(backend='ollama', model='{recipe_dict.get('name', 'my-jw-model')}')",
        "```",
        "",
        "---",
        "",
        "⚠️ Este modelo deriva de publicaciones con copyright de Watchtower Bible and "
        "Tract Society. Su uso es responsabilidad del usuario; no redistribuyas los pesos.",
    ]

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
